### ISSUE TITLE
Fee reimbursement for trade 6I6TG

### ISSUE THREAD

**Issue by waleehoohaa** [bisq-network/support#1015]
![6I6TG](https://user-images.githubusercontent.com/93359441/139361821-2d9da170-ce12-45b1-b806-5023ab0c6652.jpg)

Maker:  28e76fd1c459800bc5d988bd5f46828fd4b5ec569a132c1b749b172e4f0e1938
Taker: 8a801c4072c52c6940f8aca621b92881b0128484b9852ac75a625aa3af88bf36
Deposit: 54621a9e53aee4dcbb25da58a11b9bec963347a35ff0e49aaee7aafced068012

Bisq version: 1.7.4
BTC address for reimbursement: bc1qzqt0x26mf0a9phvmn0eg67jup6vgdlfh9seqxv

Other notes: The trade failed because payment details were not shared during the transaction. Mediator Pazza advised requesting reimbursement for the trade and miner fees. Please reimburse the trade/miner fees to the above address. Thank you!

**Comment by pazza83** [comment]
Hi @waleehoohaa thanks for opening this ticket.

I can confirm I was the mediator for this trade and that the trade was failed due to lack of payment information being available.  As such I cancelled the trade retuning security deposits to both traders and the trade amount to the seller. I also requested you both to raise an issue here to be compensated for the miner / trade fees incurred.

**Comment by leo816** [comment]
Payout made with #1028
