### ISSUE TITLE
Enabling funding for on-boarding newbies without bitcoin

### ISSUE THREAD

**Issue by CoenKuij** [bisq-network/support#117]
One of the disadvantages of Bisq is the fact that you need bitcoin to acquire bitcoin. This makes it impossible for newcomers to use Bisq and they need to first acquire bitcoin from friends or via KYC/AML exchanges. This is not desirable.

Therefore I would like to propose a funding mechanism for on-boarding purposes where people who wish to do so can lend money to someone without bitcoin who wishes to acquire bitcoin using Bisq.
To eliminate the risk of not getting back the bitcoin, the bitcoin shall be stored in a multi-sig contract where the newbie can only spent it when either an arbitrator or the funder also signs. The bitcoin can also be spent when the funder and/or the arbitrator signs.

**Comment by alexej996** [comment]
Without any bitcoin required for trading in Bisq you will open up Bisq to spam attacks.
Taking and making offers at no cost until it becomes unusable by legitimate users.

It is not hard to earn BTC these days. I never bought BTC myself, everything I have is what I earned for various work, most of which was for Bisq DAO. Now that the DAO is out, you can earn your BTC while working for an open source project in a decentralized way.

The only problem with earning first BTC with the DAO is that you get paid in BSQ not BTC. Which would require you to exchange them for BTC in Bisq. You can pay the trading fees in BSQ since version 1.0.1, but you still can't place a deposit in BSQ, so that still requires you to have BTC in order to trade in the app.

You can lockup your BSQ for reputation in the client. Which should remove this requirement.
So it is possible to get into cryptospace without ever using fiat currency with the Bisq DAO.
And you never need to expose your identity.

**Comment by pazza83** [comment]
Closing as stale
