### ISSUE TITLE
Fee reimbursement for trade IdpnGur

### ISSUE THREAD

**Issue by aphex3k** [bisq-network/support#1326]
<img width="1470" alt="Screenshot 2023-01-23 at 7 42 33 PM" src="https://user-images.githubusercontent.com/433270/214208108-1f34c689-b3ac-4dbd-bf6f-c9046e7a7025.png">

<img width="1470" alt="Screenshot 2023-01-23 at 7 42 18 PM" src="https://user-images.githubusercontent.com/433270/214208120-9096d4ef-87fd-4b73-bfec-6610ca5b160a.png">

Maker:  a3cc946b413762dc11bae97b831707f17c45bd00fb3b641a925b64792c93a4c4
Taker: 441d1fbde14604d891649b81666be2fc205d446513fa82ec1d2177edb50ad67a
Deposit: n/a
BTC mining fees lost: 0.00003752 BTC
Trade fees lost, please state if BSQ or BTC: 5.21 BSQ

Bisq version: v1.9.9
BTC address for reimbursement: 1Lf2K55uLXnYNqzggTSJzjAGLzA4wmgwf9

I am the taker of this trade and I would like at least the taker fee of [5.21 BSQ](https://bisq.mempool.emzy.de/tx/441d1fbde14604d891649b81666be2fc205d446513fa82ec1d2177edb50ad67a) reimbursed.

Note:
This is a different error from #1317, #1316, and #1311 with a different peer but the same payment method as the 3 previously mentioned transactions.

I have complete several transactions since this erroneous one using the same payment method without problem.

**Comment by ghost** [comment]
@leo816 ACK for reimbursement 3752 sats + 5.21 BSQ.

@aphex3k Thanks for the detailed failure reports.  
This issue is top priority & we're working hard to fix it, sorry it is causing frustration.
If you can supply bisq logs to a [support agent on Matrix](https://bisq.wiki/User_support#Via_Matrix_bisq.chat) it might help, particularly it would be helpful to obtain logs from both peers in a failed trade such as this.

**Comment by pazza83** [comment]
@aphex3k has provided logs to myself and I have passed them onto @jmacxx

**Comment by leo816** [comment]
Reimbursement made with #1341
