### ISSUE TITLE
Fee reimbursement for trade QBLD1O

### ISSUE THREAD

**Issue by bisqr19r** [bisq-network/support#1363]
I am BTC buyer (maker) of a failed trade. Note: Payment method hidden for privacy in image.

![Screenshot from 2023-03-21 16-45-33-edited](https://user-images.githubusercontent.com/128556834/226776876-0965044b-e2d7-4f4c-aaf0-0dfaeb2a1e35.png)

Maker:  2fafec6f15c6465547da5d3fde2a0d1d83e1455053fb0bc39075e3d3f975f2a9
Taker: ad094c99c4636a85c74ca3447a06510b2472d291ae2f382ed989a0e5145738d0
Deposit: N/A
BTC mining fees lost: 0.00002940 BTC
Trade fees lost: 0.18 BSQ

Bisq version: 1.9.9
BTC address for reimbursement: bc1qmgzcckl4u6v5e2ggzwgfc6rmlga0y04tzs4spl

**_Question: am I allowed to delete the SPV file and resync during this refund, or would that cause problems?_**

Error was: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

Thank you. :smile:

**Comment by darawhelan** [comment]
Thank you @bisqr19r 

Looks like this trade failed as either yourself or the buyer's DAO was out of sync.

You can check the sate of your DAO in the Bisq application. Go to DAO and then click the 'Network monitor' tab. Your DAO status will then be displayed. If it is out of sync it will prompt you to resync.

For this trade you lost:

Miner fees: 0.00002940 BTC
Trade fees: 0.18 BSQ

I will ask the reimbursement agent to make send you the sats back in the next reimbursement cycle (might be in April or May).

>Question: am I allowed to delete the SPV file and resync during this refund, or would that cause problems?

Yes you can do, but this issue was most likely caused by one of you being out of sync with the DAO as both maker and taker transactions completed successfully.

**Comment by bisqr19r** [comment]
Thank you @darawhelan
