### ISSUE TITLE
My bitcoins have disappeared from my wallet

### ISSUE THREAD

**Issue by Harsenx** [bisq-network/support#1368]
I've done several spv resync, but suddenly my balance is zero and there is a repeating messagge aperaing to my screan.

**Comment by Harsenx** [comment]
Atención
La transacción de tasa de creador para la oferta con ID 9DUOVYJD es inválida.
ID de transacción=23c4e208e6f937a442d3698a287aabe4c34bbd4202f53241d3ba8f71b1debab0.
Por favor vaya a "Configuración/Información de red" y haga una resincronización SPV.
Para más ayuda por favor contacte con el equipo de soporte de Bisq en el canal de Bisq de Matrix.

**Comment by MwithM** [comment]
Hi, it will probably be easier to help you on matrix bisq.chat

Two options to do right now, since you seem quite desperate:

1. Make sure noone spent the BTC corresponding to that private address, one idea is to import [watch keys](https://bisq.wiki/Wallet#Understanding_the_Bisq_Wallet) to an external wallet.
2. Import private key into a fresh new Bisq instance. https://bisq.wiki/Switching_to_a_new_data_directory

**Comment by Harsenx** [comment]
Thanks for your help, unfortunately I´ve touch and managed too many program datas, I decided to restart with the seed words. I hope it works

**Comment by Harsenx** [comment]
I suposse I will loose my signed accounts, is there any way to import them.

**Comment by MwithM** [comment]
Yes, https://bisq.wiki/Backing_up_application_data
