### ISSUE TITLE
Fee reimbursement for trade pNNtIi

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1412]
![image](https://github.com/bisq-network/support/assets/63785272/0c0b55e4-cd07-4b85-aedf-347adf8bb632)

Maker:  f581375258654311e097edd91b51f8f22d66ba632ac57746572a7a0a0be33773
Taker: 8712e60cb284c37b96883dec1a433b058cfb847ae2a96b445981bf741db2ce1d
Deposit: 802fbc5a70d0ba8574e404a9b5bbea2b5f6a721a08397bea76924d9f3e589c62
BTC mining fees lost: 0.00041280 BTC
Trade fees lost, please state if BSQ or BTC: 0.0015 BTC

Bisq version: 1.9.10
BTC address for reimbursement: bc1q3l92sx26ewrr77ycyudrg90k6aec4j5pm8raay

Other notes:
![image](https://github.com/bisq-network/support/assets/63785272/03e8096b-8375-4ba8-91a5-df02fcd60718)

**Comment by darawhelan** [comment]
@Akira45-0 

This trade did not fail.

Bisq is giving you a false error. Likely due to the amount of time the deposit took to confirm.

The multisig has been created: https://mempool.space/address/bc1qn0z7hc7m997meztjn3fswe6znz65gzfgsvmm5n58hk9gzwrhw43qt70jj4

This trade is ok to complete.

I would recommend opening mediation confirm for your peace of mind.

**Comment by Akira45-0** [comment]
OK, I have moved the trade to open trades, now it has no red exclamation marks and looks ordinarily except for the fact that Bisq still waits for deposit transaction confirmation, which is already confirmed.
Should I do SPV resync?

**Comment by darawhelan** [comment]
No, I would not do an SPV resync at this point (but only because it takes me a while, if you are using a fresh instance it might be the easiest way).

I would open mediation and explain to the mediator you will be unable to confirm payment due to a bug.

Once you receive payment the mediator can make the mediation proposal.

Once accepted and paid out the trade should move to history and avoid the need for an SPV resync.

**Comment by Akira45-0** [comment]
I have restarted Bisq without doing SPV resync (which takes reasonable time at my instance) and now the red marks are gone and Bisq has recognized the state of the trade and the deposit tx correctly, so I made the XMR payment and I'm waiting for the peer to confirm reception ("Message of payment sent but not yet received by peer"). We'll see how it will turn out.

**Comment by Akira45-0** [comment]
The trade is completed successfully and the issue can be closed. Thank you.
