### ISSUE TITLE
Reimbursement for trade 879901

### ISSUE THREAD

**Issue by Steadynslows** [bisq-network/support#1590]
Trade ID: 879901-0297d593-33b5-495e-aff5-3d2bdddddf24-1914

Dispute Details: Buyer never sent payment nor responded to my message on Jan. 18, 2024. The funds were sent to arbitration on 8th February. 

GitHub handle of mediator: @pazza83 

TXID: fb3fca06d594871d054453220ef87f3b2f2f69374c41c4f84b451dce2bc4
f788

TXID: 954d9da2eeedba865595550a77a1b0fa9b3b85bd21ab94758fc90261fc85
1427

Additional Details: I failed to respond to the arbitration because of family emergency travels that caused me to be away from my computer until now. Always enjoyed using Bisq and have 50+ completed trades as well as holding BISQ. It would mean a lot to me if the DAO can understand this was a one-time situation and I have always communicated and responded on time. 

The amount was 0.01BTC at the time of the trade BTC Price was 43951 making the amount 440. 
I'm only asking the DAO for the price at the time of the trade in the amount of 188 BISQ.
Thank you all for your time.

**Comment by pazza83** [comment]
Hi @Steadynslows 

I disagree that you should receive compensation.

The BTC buyer sent proof of payment (happy to provide you this on request).

Buyer is also signed (Time since signing: 597 days).

- Trade was taken on 18 January 2024.
- The BTC buyer sent you payment in January 18th (proof provided). 
- The BTC buyer opened mediation on 22nd January as you had not released the bitcoin and they had tried chasing you up in trader that with no response from yourself
- I tried contacting you in mediation but you did not respond.
- I made the mediation proposal to complete the trade on 25th January to complete the trade.
- Buyer accepted the mediation proposal you did not reply.
- I assume you also did not respond to @refund-agent2 and as a result lost your deposit.
- Your first message to me was 17th March, this is two months after the trade. This is the first time you said you did not receive payment.

I suggest you check your bank for a deposit of $440 sent on 18th January 2024, hopefully the payment will be found. Failing that I would ask you to contact the BTC seller.

Thanks for being a Bisq user but I am afraid on this occasion you did everything wrong by completely not responding to your trade peer and mediator.
