### ISSUE TITLE
Clarify BSQ reimbursement

### ISSUE THREAD

**Issue by huey735** [bisq-network/support#267]
If I understand correctly, when reimbursing BTC, the reimbursement goes back to the traders BTC address visible in the transaction. How does it happen for BSQ?

**Comment by KanoczTomas** [comment]
Hm this is a valid question. @ripcurlx (feel free to mention other devs) a classic block explorer does not see it is BSQ, so is there a good way to verify fees were paid with BSQ and how to reimburs it? Perhaps those trades could be pointed to the DAO reimbursement request, and new BSQ would be sent to for reimbursement. Any thoughts?

**Comment by ripcurlx** [comment]
@sqrrm Do you think you could answer this?

**Comment by sqrrm** [comment]
In the case of using the reimbursement functionality in the DAO it works just like a compensation request. Everyone votes on the reimbursement proposal and the user provides own BTC that gets colored as BSQ. This is not meant to be used for common small claims like lost fees due to bugs and such. Any voting need to be limited as contributor attention is a limited resource.

Out of band reimbursement, which we've done so far, can be done any which way, I haven't followed exactly how it's done.

**Comment by KanoczTomas** [comment]
@sqrrm thanks! Btw if the fee is paid with BSQ and goes on chain = has to be reimbursed it was effectively burned, right? So if one wants back BSQ can use the DAO if wants back the underlying BTC, can get it back via opening a support ticket.

**Comment by sqrrm** [comment]
@KanoczTomas you can see the BSQ txs at https://explorer.bisq.network/ to verify how much was burnt in a tx. It's sometimes a bit slow to update the fresh txs but eventually you should be able to see how much was burnt in every tx. That's probably the easiest way to verify that some amount of BSQ was burnt, and the tx should correlate to whatever other data you have, such as txid.

**Comment by xbyvee** [comment]
I have 600-800 BSQ lost in failed trades, I had no idea this wouldn't be reimbursed and I incorrectly? lodged reimbursement requests. Will I ever see it again? It's a lot of money to me, I didn't think I'd lose it

**Comment by KanoczTomas** [comment]
@xbyvee you have received a refund in btc, you can open a reimbursement request in the dao and use that reimbursed btc to color it and get back your BSQ. At least if my understanding is correct. @ManfredKarrer @ripcurlx @sqrrm can you please confirm?

**Comment by xbyvee** [comment]
Thanks for the response @KanoczTomas 

This is the first time I've had to get BSQ back from failed trades so I'm not really sure how to do use the DAO to do it, Is there a guide or instructions somewhere? I've tried searching Github/The forum and I can't find anything.

**Comment by xbyvee** [comment]
Can anyone help me here that knows how this works? Is there a github proposal example I can use, can I batch my failed trades together (about 10 trades totalling about 700BSQ). If I can't get this BSQ reimbursed it doesn't give me confidence to use Bisq anymore due to the amount of failed trades I've had and how high the trade fees are.

**Comment by m52go** [comment]
> @xbyvee you have received a refund in btc

@xbyvee if this is the case, can you just use your reimbursed BTC to buy BSQ? Sounds like there should be no need for a reimbursement request.

**Comment by xbyvee** [comment]
I got $64 USD worth of BTC back when I spent about 800USD worth of BSQ on trade fees from the failed trades.

**Comment by ripcurlx** [comment]
> @xbyvee you have received a refund in btc, you can open a reimbursement request in the dao and use that reimbursed btc to color it and get back your BSQ. At least if my understanding is correct. @ManfredKarrer @ripcurlx @sqrrm can you please confirm?

Yes that should be the way to go. Prove the burned BSQ fee in the explorer and add additional information why you need to get this amount reimbursed within the Bisq DAO. As we didn't have this case so far, there is no example reimbursement request to look at.

**Comment by m52go** [comment]
An updated proposals doc is coming, which will cover this. 

For now, here are basic steps:

1. Make a new GitHub issue in this repository for your reimbursement proposal (a new one that combines all details of all trades). Be as specific as you can about the problematic trades (links/txids wherever possible) and include any other pertinent information so DAO voters can verify what you're requesting. If the BSQ explorer links are not showing correctly yet, don't worry.

2. File the request in the Bisq DAO as a reimbursement request (DAO --> Governance --> Make Proposal --> Reimbursement Request).

In the form:
* Make sure your name/nickname matches the GitHub identity you use to make the GitHub proposal from step 1.
* The `#` in `https://bisq.network/dao-reimbursement/#` is the issue number of the GitHub proposal you created in step 1, so `https://github.com/bisq-network/proposals/issues/120` should be entered in the DAO as `https://bisq.network/dao-reimbursement/120`.
* Make sure you get all information in the DAO form correct because it cannot be changed once submitted (only deleted and submitted again).

**Comment by sqrrm** [comment]
In my opinion we should not use the reimbursement proposals for loss of funds due to bugs. It would be better if this could be refunded right away by a contributor whose role it is to handle such issues. This contributor would then request compensation for all the refunds given in their compensation request. It isn't reasonable to assess these smaller reimbursement proposals otherwise and the refund process would be much faster if handled by a contributor. I don't mean to say that 800 BSQ isn't a lot for an individual but rather that it would be untenable to handle a lot of these reimbursement requests.

What I think we should reimbursement proposals for is larger reimbursements, where for example funds have been burnt due to malicious activity or other larger events that's harder to cover for an individual contributor. Those kinds of events might also warrant more scrutiny than common bugs.

**Comment by m52go** [comment]
Makes sense...we should clarify guidelines for reimbursement requests. I thought the amount was big enough to warrant it in this case, but it may not set a good precedent.

**Comment by sqrrm** [comment]
I agree that the amount might not be that small, but it's not really contentious. Asking for a vote on something like that is not great more on the principle of delegating routine work than the amount. If we can't find another solution, then so be it, but it adds work for all contributors to verify the reimbursement requests.

**Comment by danielv1234** [comment]
I have same problem, lot of bisq  paid for fees, nothing reimbursed.
