### ISSUE TITLE
Reimbursement request for trade 49320

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#502]
![cdah7LM](https://user-images.githubusercontent.com/45833017/93697636-f0240980-fb15-11ea-9c47-3fb40a702af2.png)

Maker: 71a7f0d2a5be250e774d8a80ccdeb387f3afd9c15649b559de8c17bbf8281f59
Taker: 8805b5f3ad1ba191cb06d9c643df51b009a63df3828ca7e6167961d626370230
Deposit: dda9eb04c7ed6a05ec33b131d34f06866c47b45cd923e4269019bc430d450fab

TradeID: 49320
Time/Date: 24 aug 2020, 22:10
Payout txid: N/A (funds locked)
Trade amount: 2.00 BTC
Security deposit (buyer/seller): 0.42191307 BTC / 0.42191307 BTC
Mediator: @leo816 (sjlho4zwp3gecspf)
Mediator secret: N/A

Bisq version: 1.3.8

I am the BTC buyer as taker. There was a bug with this trade, listed as failed trade. Trade partner has become unresponsive. I did not make the XMR payment. The suggested mediator payout was: BTC buyer: 0.42191307 BTC, BTC seller: 2.42191307 BTC

![g0KH7Bl](https://user-images.githubusercontent.com/45833017/93697738-f7e3ae00-fb15-11ea-93de-34ddd2f08553.png)

Additional information:
This trade failed right from the start at my end, and ended up in the failed trades list.
Trade partner sent a message in the chat of [TradeID LMKSE38C](https://github.com/bisq-network/support/issues/502), to ask why i had not sent the payment for TradeID 49320 yet. I explained the failed trade situation to the trade partner and attempted to unfail the trade. This was not possible because i was missing the Delayed PayoutTx on my end. I asked the trade partner to share the Delayed PayoutTx with me so that we could safely unfail and continue our trade, alternatively he could open a mediation request to get the trade ( 49320 ) canceled. After that there were no more replies to my messages, all communication stopped from their end.

Effectively the trade partner is the only one that can do anything with the funds locked in TradeID 49320, as i cannot move it to arbitration (donation address) because this is exactly the Delayed PayoutTx i'm missing and why the trade failed on my end.

When I realized did not have the Delayed PayoutTx on my end, and I had no way of unlocking funds for arbitration in case there was a conflict or the trade partner would become unresponsive, I decided to not pay TradeID LMKSE38C. Such that in an unfortunate event, there would be funds available through mediation/arbitration to compensate for the locked funds from this trade (TradeID 49320).

I have no way of getting my security deposit back with an unresponsive trade partner that has sole possession of the Delayed PayoutTx.

Request:
To get back my security deposits and part of compensation, I'm requesting a rebalancing of these two trades ( [49320](https://github.com/bisq-network/support/issues/502) + [LMKSE38C](https://github.com/bisq-network/support/issues/501) with the funds available , which is 0.91 BTC.  

Currently with 30 day avg this would be 16069.22 BSQ at a price of 0.00005663 BTC/BSQ (2020-09-22)

Bisq Proposal ID: e300617df6d48ff8b946127c2421771249824fe74b7c153a6c2d3d80e81e50aa

@chimp1984 created a more comprehensive [overview of the situation](https://github.com/bisq-network/support/issues/502#issuecomment-696376150) than i did.

I understand the situation can be confusing, please inquire if things are unclear.

**Comment by wiz** [comment]
Who was your mediator for this trade? You will need to tag them and have them confirm the details of your claim.

> I have no way of getting my security deposit back with an unresponsive trade partner that has sole posession of the Delayed PayoutTx.

Since this isn't actually a typical reimbursement request for funds that were donated to Bisq, but instead **a reimbursement for funds lost due to a bug in Bisq**. the circumstances need to be considered by the DAO stakeholders carefully, mainly: 

If the DAO refunds you the 0.42 BTC that's locked up, **you could still complete the trade normally and get your 0.42 BTC security deposit back**. AFAIK there is no precedent for this type of refund scenario, especially this quickly. For example, the DAO cannot be sure you are also not the other party of the trade and holding both keys to the locked up funds.

**Comment by invertedbobb** [comment]
@wiz What? Why would i be trading with myself? If the reason would be to scam the DAO for 0.42 btc i wouldn't be making many other trades (44) over the weeks before that and paying all the fees ( i paid a total of 0.24 btc in fees with this trade partner ), let's not even talk about the losses that would cause because of price difference.
Now sure, i can't think of some way to prove i'm not trading with myself. If there is some way i can provide this proof i'd love to hear it.

**Comment by chimp1984** [comment]
@invertedbobb 
The security model of reimbursement eiher by the refund agent or by the DAO direclty is based on the fact that the funds from the trade are sent to the burningman donation address (the burningman trades the BTC to BSQ and burns the BSQ).
If the funds are not sent there a malicious trader could easily exploit that model by doing a self trade, then bring it to refund agent with one peer clearly breaking the contract (e.g. not responding) and then if he gets refunded from the RA, wait a while and then do the payout of the locked 2of2 MS to himself as he was both traders he has both keys and can pay out any time after he received the refund from the RA/DAO.

This is the reason why the DAO cannot accept reimbursement requests if there is no delayed payout transaction done. 

I understand that there might be a bug or rare network conditions which caused your case, but you also need to understand that the DAO cannot simply ignore its security protection. We will find a solution for your particular probolem but less give it more time and due dilligence.

I will investigate if there can be a bug or a condition where you did not receive the deplayed payout tx. I would need your help for that investigation (e.g. providing log files). Could you PM me on keybase (same username as I use on GH).

**Comment by chimp1984** [comment]
I can confirm the validity of the deposit tx:
https://blockstream.info/address/3GHPq6DW7QJ9oNbzyX5ozrMeBJwFan8fx2

But as @invertedbobb stated there is no delayed payout tx.

@leo816 Why did you suggest a refund to the not responding peer? Can you confirm the data stated here?

**Comment by chimp1984** [comment]
Here is my suggestion for how to deal with the issue with the 3 related cases of @invertedbobb:

https://github.com/bisq-network/support/issues/502
Trade 49320:
Buyer has no del. payout tx. No XMR sent. Seller not responding.
Trade amount: 2.00 BTC
Security deposit (buyer/seller): 0.42191307 BTC / 0.42191307 BTC
Peers onion: 47kfb2ryxubechhw3vez5x2vnw5mibascf47qki6zdoo6jsv

https://github.com/bisq-network/support/issues/501
Trade LMKSE38C:
Buyer has made del. payout tx. No XMR sent. Seller not responding.
Trade amount: 0.70 BTC
Security deposit (buyer/seller): 0.1050 BTC / 0.1050 BTC
Peers onion: 47kfb2ryxubechhw3vez5x2vnw5mibascf47qki6zdoo6jsv


https://github.com/bisq-network/support/issues/500
Trade: MZEFILM
Buyer has made del. payout tx. XMR sent. Seller not responding.
Trade amount: 2.00 BTC
Security deposit (buyer/seller): 0.42191307 BTC / 0.42191307 BTC
Peers onion: 47kfb2ryxubechhw3vez5x2vnw5mibascf47qki6zdoo6jsv


So buyer has locked up from the 3 trades with the same not responding peer in total:
0,42191307 BTC + 0,1050 BTC + 2,42191307 BTC = 2,94882614 BTC .
The not repsonding peer do not deserve any refund from his security deposits but should get back his trade amounts of the 2 trades where no XMR was transferred.
For compensating for the lost time, trade opportunity and effort for the DAOreimbursement @invertedbobb should receive the deposits from the peer of all 3 trades. As the peer did not respond it is a clear protocol violation which leads to loss of the deposit.

Peers deposts are: 
0,42191307 BTC + 0.1050 BTC +  0.42191307 = 0,94882614 BTC

So funds @invertedbobb deserves in Total are: 2,94882614 BTC + 0,94882614 BTC = 3,89765228 BTC


The 2 trades where the del. payout tx was made have in total: 
Trade LMKSE38C: 0.70 BTC + 0.1050 BTC + 0.1050 BTC = 0,91 BTC
and Trade MZEFILM: 2.00 BTC + 0.42191307 BTC + 0.42191307 BTC = 2,84382614 BTC
in Total: 3,75382614 BTC
Those funds can be used for reimbursement as they got burned to BSQ via the burningman.

The still locked up funds from trade 49320 are not available yet.

From the 3,75382614 BTC @invertedbobb deserves at a minimum the  2,94882614 BTC to not experience a loss or 3,89765228 BTC including the deposit from the peer as extra compensation as usual in such cases.
As we have only 3,75382614 BTC available from the funds which got sent to the burningman @invertedbobb has to accept to receive that instead of 3,89765228 BTC (missing 0,14382614 BTC from remaining peers deposits).

If the not responding trader cooperates and publishes the delayed payout tx and opens an arbitration case he will get the trade amount from the 2 trades (2.7 BTC) where no XMR was transferred and invertedbob will receive the missing part of the peers deposits (0,14382614 BTC).

I think that solution is fair specially as the peer seems repeatedly violated the trade and dispute protocol. He still can get back his locked up funds if he cooperates with unlocking the funds from trade 49320.
The mediator has sent him a private notification message as well.

It is up to DAO voters to decide what they think is the best solution here. The above is only my private opinion.

**Comment by invertedbobb** [comment]
@chimp1984 Yea the missing funds are unfortunate but my main concern is getting the bulk of it back and compensation as far as possible. We'll see if the trade partner ever shows up again, i doubt it (from past experience), but if that were to happen, we can handle it from that point and refer to this topic.

I've created a separate DAO request for [MZEFILM](https://github.com/bisq-network/support/issues/500), as it is unrelated to the rebalancing of the funds.

I'll make a DAO request for the funds available here to re-balance these two trades ( [49320](https://github.com/bisq-network/support/issues/502) + [LMKSE38C](https://github.com/bisq-network/support/issues/501) ), which is 0.91 BTC.

Currently with 30 day avg this would be 16069.22 BSQ at a price of 0.00005663 BTC/BSQ (2020-09-22)

**Comment by wiz** [comment]
@leo816 can you please respond to this case?

**Comment by leo816** [comment]
I can confirm the data @invertedbobb provided, the BTC Seller did respond initially and it seems that after the buyer asked for the delayed payout transaction he stopped replying. Given that the buyer didn't make the xmr payment and that the seller was probably new to this situation, I didn't think it was appropriate to take his security deposit. I sent him a private message to try and get hold of him.

**Comment by Bisq-knight** [comment]
@leo816 
> I sent him a private message to try and get hold of him.
On keybase? or in Bisq? Since he's the quiet party in 3 trades, would be nice to try and reach him by other means

**Comment by Bisq-knight** [comment]
Btw, @chimp1984 I think there's a typo on your math, or I'm missing something:

> So funds @invertedbobb deserves in Total are: 2,94882614 BTC + 0,94882614 BTC = 3,89765228 BTC

or I didn't quite get which outputs Buyer should get. Can you elaborate?

I put it on a table format so it is easier to discuss:

| Trade Id  | Seller Deposit | Buyer Deposit | Trade amount | total amount | Seller     | Buyer      | Reason                                                  |
|-----------|----------------|---------------|--------------|--------------|------------|------------|---------------------------------------------------------|
| 49320     | 0.42191307 (**a**)   | 0.42191307 (**b**)   | 2       (**c**)     | 2.84382614   | 2  (**c**)        | 0.84382614 (**a+b**)| Buyer did not send the payment                          |
| LMKSE38C  | 0.105  (**d**)        | 0.105    (**e**)     | 0.7    (**f**)      | 0.91         | 0.7  (**f**)      | 0.21    (**d+e**)   | Buyer did not send the payment                          |
| MZEFILM   | 0.42191307  (**g**)   | 0.42191307  (**h**)  | 2  (**i**)          | 2.84382614   | 0.42191307 (**g**) | 2.42191307 (**i+h**) | Buyer sent the payment                                  |
| total     | 0.94882614     | 0.94882614    | 4.7          | 6.59765228   | 3.12191307 | 3.47573921 | Seller gets 47.32% of total, Buyer gets 52.68% of total |

**Comment by Bisq-knight** [comment]
Thinking over it and rereading what @chimp1984  posted. I agree.  We should essentially reimburse the total available here to @invertedbobb:  3.75382614 BTC.

@invertedbobb in that amount you are covered for the XMR you spent and a significant part of the seller's deposits (although not all of it, since it is locked). Do we agree that is sufficient compensation?

**Comment by invertedbobb** [comment]
@Bisq-knight I agree with that, this is what i requested to the DAO. 0.91 BTC (49320 & LMKSE38C) + 2.84 BTC (MZEFILM)

If we / you can get a hold of the BTC seller again, he can claim the remaining funds that are currently locked up, and where he is the only one that has  the delayed payouttx available to release it to the donation address.
The situation can be handled from there with him, i don't need to get involved.

**Comment by Bisq-knight** [comment]
Agreed. Please post both proposals' transaction IDs here for reference so people reading the proposals can know which exact proposal this pertains

**Comment by invertedbobb** [comment]
Added Bisq Proposal ID in OP.

**Comment by Bisq-knight** [comment]
Just for the Record:

Cycle 17
Request granted
