### ISSUE TITLE
Wrong balance shown after update to version 0.6.2 or 0.6.3

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#58]
@JoKeyser commented on [Sun Jan 21 2018](https://github.com/bisq-network/exchange/issues/1247)

First, thanks for your great work. I've been dabbling with the system last month and it works really well.

I've started using version 0.6.1, but after an update to 0.6.2 or 0.6.3 (I'm not sure which one), my transaction balance is shown as 0 for some reason, which isn't right. As "proof" I attach a screenshot of Electrum, imported through the seed words - it shows the funds I know are correct, and have been shown in Bisq until the upgrade. I've tried downgrading to 0.6.2 and 0.6.1, but that doesn't change anything (maybe files got upgraded?).

Here the (somewhat anonymized) screenshots:

![bisq_problem](https://user-images.githubusercontent.com/8722846/35195035-402183b4-feb5-11e7-9f98-f02fa916632a.png)

Here the 'correct' view of the balance in Electrum:
![electrum](https://user-images.githubusercontent.com/8722846/35195053-6d55b4f4-feb5-11e7-867a-7c421bec01d7.png)

I'm happy to provide any more information that may help you, including my files etc (over encrypted email), if that helps. I'm using the Bisq version from Arch Linux's AUR.

---

@JoKeyser commented on [Mon Jan 22 2018](https://github.com/bisq-network/exchange/issues/1247#issuecomment-359433388)

I should say that I'm not sure whether I made the last transaction within Bisq or with Electrum... if the latter, maybe it's natural not to work in Bisq anymore?
(And maybe I've mis-interpreted that the upgrade has anything to do with it, and all that happened was that Bisq caught up with the history that may have been "tainted" with Electrum's transaction...)

**Comment by cbeams** [comment]
@JoKeyser, try resyncing your SPV file and see if that fixes your available balance in Bisq. You can do this at `Settings->Network info->Resync SPV chain`.

**Comment by JoKeyser** [comment]
@cbeams thank you for having a look.

Unfortunately resyncing didn't help. I clicked `Delete SPV file and resync` (and restarted, sync'd, restarted) in versions 0.6.1, 0.6.3 and 0.6.4. In each case, my wallet balance is flat zero.

What's odd to me is that Electrum and Bisq show a divergent transaction history from December 11 onwards. And I'm *nearly certain* that Bisq showed the correct balance until I upgraded a few days ago. Now it's inconsistent with the transaction values it shows itself:

```
-0.00386898
-0.00438967
-0.0310
+0.0310
-0.002560
-0.000980
-0.000824
+0.0110
+0.0110
-0.00113520
-0.00026760
-0.000356
+0.0110
--------------
+0.01861855 != 0
```

Although Electrum shows that correct balance, maybe there's a better way to establish the "true" history without it, since it doesn't show the entire transaction history like Bisq... maybe that would hint at what went wrong, too. Do you have a suggestion what to look for, say with an online blockchain explorer?

**Comment by JoKeyser** [comment]
For the record, same issue with v0.6.5.

**Comment by JoKeyser** [comment]
I've sent a small amount a Bisq-generated address, and that got added correctly. That is, Bisq shows that amount as (wrong) grand total balance, while Electrum added it correctly to the existing amount.

**Comment by cbeams** [comment]
Closing as dropped / out of date.
