### ISSUE TITLE
Fee NOT reimbursement for trade giio5op

### ISSUE THREAD

**Issue by BisqTor** [bisq-network/support#620]
Fee NOT reimbursement for trade giio5op

Are you kidding me??? 
I waited 8 months to get my money back and BISQ returns 10% of what I had? Then that's it? Is that BISQ? Stealing money?
@leo816 paid me 0.0007 btc and closed the issue?
My security deposit was 0.006 btc.
Where are my money? On @leo816 wallet or in any Bisq wallet?

If you don't want to be robbed, don't use BISQ?

Link of my issue:
https://github.com/bisq-network/support/issues/396

**Comment by leo816** [comment]
Hi, please contact us through keybase. Some of the payouts have been done now and the remaining will be done in the coming weeks. Please remember that the payout is made privately from someone's pocket and then the fee reimbursement agent gets reimbursed from the amount he put out. risking losing money with the exchange rate so please don't make such accusations. If there has been an error I will look into it and will make the remaining payout accordingly. Please remember that the issue you had 8 months ago started with a different role holder and he stopped answering which is why i've had to make the payouts manually.

**Comment by BisqTor** [comment]
What is keybase?
How can I acess it?

**Comment by leo816** [comment]
keybase is a messaging app. you can download it on your phone or computer and there you can talk with me or our support team to solve these issues.

**Comment by pazza83** [comment]
Hi @BisqTor I am closing this issue. If it is still unresolved please reach out to me on Keybase: https://keybase.io/team/bisq

My username there is: pazza
