### ISSUE TITLE
Reimbursement and compensation for trade CCfg0KQ

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#684]
Hello. I would like to ask for reimbursement and compensation. I have sent the XMR correctly. 11 days have passed already and the BTC seller had not released the coins, so I ask to reimburse me 2 BTC of the trade amount + 0.30 BTC of my security deposit + 0.30 BTC from the seller's deposit as a compensation, that is 2.6 BTC total. The 30-day average BSQ/BTC price is 0.00004202 BTC, so I ask for 61875.3 BSQ total.
![grafik](https://user-images.githubusercontent.com/63785272/103369733-30a70200-4acb-11eb-91ae-614e2aaf4b16.png)
Maker:  6b1ee80454d5dc0c857ef7a2851a143e00e484b0d5273ddabba9eda37872912b
Taker: 6c18f842574f29c25cb17f8978dbff283bd050dd32a55a808c09fc3e84368723
Deposit: 3bc9977aaa9bc31cd90341da824c78e4ea16d1b4f6b7927314c55f9d8a9007ef
Delayed payout: 9003a59756e6846776ce9109972f23404a532a93991bf0f7ed4a90d61498b07b
Delayed payout sent to: 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC
Contract hash: 5279bd995e68da2071711954d70cc2dd7332c1eaa64e603aff49e3bf18c30800

Bisq version: 1.5.3

Other notes: Mediator for this trade was @leo816  and arbitrator was @refund-agent2

**Comment by huey735** [comment]
This should be solved through the Arbitration process.

**Comment by Akira45-0** [comment]
> 
> 
> This should be solved through the Arbitration process.

The arbitrator told me that he can't refund more than 0.5 BTC so I have to submit a request on Github.

**Comment by Akira45-0** [comment]
Key from the arbitrator: 5ef0dc1471d8f4490a99d73127ad0131

**Comment by refund-agent2** [comment]
Arbitrator key is correct.
I have checked XMR payment and delayed payout tx amounts.
Seller did not respond to mediator or refund agent. 
2.6 BTC payout should be made to buyer, but the amount is too big. 
The DAO should approve reimbursing 2.6 / 0.00004202 = 61875.3 BSQ
@Akira45-0 submit DAO reimbursement request TXID.

I'm trying to submit mediation and arbitration result verification.

**Comment by chimp1984** [comment]
I think we have to rethink how we deal with the peers security deposit. I support that the one who did the reimburesement request receives a compensation for the extra work but 0.3 BTC seems very high with current BTC price. Thats nearly 8800 USD with todays price. I think we should cap that to max 1000 USD. 

I don't argue that we should that apply immediately but I made a proposal for discussing that:
https://github.com/bisq-network/proposals/issues/292

**Comment by Akira45-0** [comment]
> @Akira45-0 submit DAO reimbursement request TXID.
ecad3025e53f6e0a6ac386b34ee4522da0651a55a727ae6d12b00fc495af6ada

**Comment by Akira45-0** [comment]
> I support that the one who did the reimburesement request receives a compensation for the extra work but 0.3 BTC seems very high with current BTC price.
Well, it's the minimal security deposit, 15%. I have a lot of money locked because somebody did not comply with the terms of the trade, and I have it locked for nearly two weeks during a bitcoin bull run, which makes me annoyed to say the least.

**Comment by chimp1984** [comment]
Yes, I know... Feel free to comment on the proposal to give feedback from traders perspective.

**Comment by Akira45-0** [comment]
I made the request in the DAO again. The tx id is e27ea87f25f8c73a822897ae492e6e6d86b356a74362ec20282cdfef456f1882.

**Comment by spx4000** [comment]
Issuing BSQ at 4202 sats is financially reckless for the DAO when the 30 day average is now 6209 sats.

Why use a far below market rate and give the user the choice of keeping the BSQ or selling to the burning man?

Akira45-0 is getting the .3 BTC security deposit, due to the delay in settlement, this seems to be a fair outcome.

@chimp1984 suggests that it is too much, and maybe the security deposits from failed trades should be shared by the trader and the DAO in some way.  I think @chimp1984 linked a discussion.

If the DAO continues with this reckless policy, it can easily become an attack vector.  I trade with myself,  I don't complete the trade, I go to the DAO and ask for BSQ reimbursement at a below market rate, I go sell all this BSQ at the market rate.


Akira45-0 has no reason to sell this 60,000 BSQ back to the burning man at 4202 when there are bids of almost 5000 sats in the order book and the current last trade price is 10,000 sats.

This will be a very expensive lesson for the DAO.

If you issued 26,000 BSQ at, for example, 10,000+ sats, and the burning man and Akira45-0 arranged to trade as occurred in the past, there is less risk to the DAO.  There would be risk to Akira45-0 that the burning man doesn't have the funds, or decides not to trade with Akira45-0.

**Comment by chimp1984** [comment]
The BSQ price had quite some growth over the past months as well as BTC so volatiliy handling gets more difficult. 
I think best is that the BM makes the trade with Akira45-0 at the price he get reimbursed, so Akira45-0 gets back his BTC value and for the DAO its a zero sum game. 
@spx4000 You bring some valid concerns and we have to observe carefully the situation, but as liquidity in the BSQ market is not that high selling 60k BSQ at the currently higher market price will not be easy and average price will likley be lower.
 
All in all we should work to reduce those cases at all. Goal was to have arbitration cases exceptional and there are still too many. I guess main issue is still not responding sellers and it is unclear what the motivation is for those cases as well how to prevent it. The financial loss for those non-responding traders is considerable so we can exclude lazyness/carelessness, UX issues IMO.

**Comment by spx4000** [comment]
Well, in the past, Akira45-0 just kept some of the BSQ he was issued from the DAO instead of selling it to @burningman3 based on @burningman3 trading records.  Why would Akira45-0 sell it to the burning man for 4202 when the market price is higher?

If you are just trying to make a swap from DAO to reimbursement, it makes sense to use a smaller number of BSQ at a higher satoshi price.  And then Akira45-0 would make the trade with burning man and thus it would be zero sum. 

The way you are letting him do the reimbursement now, you are giving him a free call option on BSQ at the strike price of 4202 sats which is deep in the money.  Burning man paid 8900 sats two weeks ago, so I don't think it's that hard to get more than 4202 as you claim.  Maybe not all in one trade, sure.

**Comment by spx4000** [comment]
Anyway, not only is it good to not give this free option, it's quite practical to make room for **this month's issuance**.  It doesn't matter what rate Akira45-0 BSQ is issued at as it will be traded for 2.6 BTC from the burning man.  So why not make it much less BSQ and then honor that rate in a trade with Akira45-0 pending a YES vote?

**Comment by chimp1984** [comment]
Maybe its better to continue that discussion at https://github.com/bisq-network/proposals/issues/292 or on keybase to not derail too much the reimbursement request.
I was in contact with @Akira45-0 a few times with bugreports and he has been super supportive and I do not think that he is trying to gain here anything. He might keep some BSQ for future trading fee or as investment.
So to summarize: I do not think that we should criticize @Akira45-0 here, but I see very well the valid concerns @spx4000 brings up and would like to find a forum where we can continue to look for a better solution.  

@spx4000 Are you on keybase as well? If so can you PM me? Otherwise continue the discussion at https://github.com/bisq-network/proposals/issues/292

**Comment by Akira45-0** [comment]
Your concern about me not becoming a billionaire by getting my own money back is very touching. It was not my idea to use 30-day average price in the reimbursement request, and this was the price at the moment I wrote the request. I am not as clairvoyant as you and I have no way to know what the BSQ price will be, mr. spx4000.

I am very sorry to disappoint you but BSQ outside of Bisq is completely useless and the only way to use BSQ is to sell it for BTC or use it as a trading fee. In case you did not notice, it's hard to sell BSQ for BTC because the market is illiquid which means that explioiting the reimbursement process is not a real option even if you have a way to magically know what the BSQ price will be.

Of course I kept part of the BSQ I received earlier as a compensation and I am still paying my trading fees with these coins, because this is the only real way they can be used. I have never sold any BSQ I received, and if I did so, I would have to buy BSQ again to have coins for trading fees, and I will be buying it for higher price, higher because of me just selling the BSQ for a higher price, mr. financial genius.

How about being concerned about the REAL ISSUE, that is the time needed to get a compensation? 46 days have passed and my funds are still locked and that's the real problem. Another problem is the 10-day mediation, which makes the whole concept of 24h trade fictious.

**Comment by refund-agent2** [comment]
Hi @Akira45-0 did you buy BTC from @burningman3 for this reimbursement?
How many BTC did you buy and how many BSQ did you spend?
It's for accounting reasons.

**Comment by Akira45-0** [comment]
> Hi @Akira45-0 did you buy BTC from @burningman3 for this reimbursement?
> How many BTC did you buy and how many BSQ did you spend?
> It's for accounting reasons.

I bought 2.3111 BTC for 55000 BSQ.

**Comment by pazza83** [comment]
Closing as reimbursement has taken place: https://bisq.markets/tx/e27ea87f25f8c73a822897ae492e6e6d86b356a74362ec20282cdfef456f1882
