### ISSUE TITLE
Reimbursement and compensation for trade 9nwxc (updated)

### ISSUE THREAD

**Issue by brndnng** [bisq-network/support#796]
Reimbursement and compensation for trade 9nwxc

I am BTC buyer, as taker.
Trade amount: 2 BTC
Deposit amount: 0.3 BTC
Reimbursement amount: 2.3 BTC / 0.00006239 BSQ (30-day average) = 36864.88 BSQ 
Reason for reimbursement: Seller did not respond.

Ticket closed on Jan 8, 2021 12:04:16 AM
Mediator node address: apbp7ubuyezav4hy.onion:9999

Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 2.30 BTC
Payout amount for BTC seller: 0.30 BTC

Reason for dispute: Seller not responding

Summary notes:
Seller never replied a single message

-----BEGIN SIGNATURE-----
302c021470784b57eedb0c1ea4a96a3cb3648711a3414d9902145af7e7f8ee5b0ce2c8b31612cbd299e5808b9f73
-----END SIGNATURE-----

Ticket closed on Jan 10, 2021 11:48:14 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.00 BTC
Payout amount for BTC seller: 0.00 BTC

Reason for dispute: Seller not responding

Summary notes:
Seller did not respond to mediation or arbitration. Trading amount too high for Refund Agent. DAO should reimburse the equivalent to 2.6 BTC.

-----BEGIN SIGNATURE-----
302c02145e3962ede67e07966accf5a80d3d0c597c3f5188021437bfa70510aed2d991462cbeb01ece47f4673ea8
-----END SIGNATURE-----

Next steps:
No further action is required from you. If the arbitrator decided in your favor, you'll see a "Refund from arbitration" transaction in Funds/Transactions

Next steps:
Open trade and accept or reject suggestion from mediator

Arbitrator secret: f908fd2372dc402672be4ae3b837ceed

**Comment by brndnng** [comment]
@refund-agent2 @Bisq-knight

**Comment by refund-agent2** [comment]
Can you re-open the arbitration ticket by selecting the ticket and pressing ctrl+O?
The amount you are requesting is correct but I want to submit a new arbitration summary.

You should edit the total amount in BSQ.

**Comment by brndnng** [comment]
I tried ctrl+O but it didn't work

**Comment by refund-agent2** [comment]
Try messaging me then.

**Comment by refund-agent2** [comment]
Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.00 BTC
Payout amount for BTC seller: 0.00 BTC

Reason for dispute: Other

Summary notes:
Seller did not respond to mediation and responded late to arbitration because of Bisq data lost, but contacted Support Agent @mwithm into the trading period. Mediator @bisq-knight did not see the issue and arbitration started. Refund agent was not alerted during arbitration period.
DAO should reimburse the BSQ equivalent to 2.3 BTC to buyer and 0.3BTC to seller. Seller has verified ownership of BTC address used for the trade signing a message with that address.

I can't reopen arbitration. You can verify signature of this arbitration resolution with Keybase.
---------------

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkZLbxYV kC7EjlRx7IOE5PM dEeQlOO0zXrJt7R 3OEeY1VBjhUYW1u 4D4Tbt4wVRn6JcP 84vofAlh8dzgp7l TaNWvQ2TdwUp2Bv utBitVNuy0RcyB1 SdvPdvND1eAExlt KyKxTraDHoXdFyd YtcVgrRyGWU0xoe LXUn32ndqtNL7cM 1tVqX8rsAoQI5VK xFGXuSKSoxvPHfc 8j2F2xjBTFMyvlG fb8dw1SOCTLsi6g IoiBtl02M6CdGgh U73ZBT3M88sjuzD Lsge9eHnr9TmGmv qRr7Lz22CsE2mCs FqNbkosAdTTziYy RJ6Ws6zYIBKjvW7 eHA0VDVDa7iZ45N QXKjEc6Mu2F83KU Nf38kkYUA16dR3t qbPhfcoTgfFUQIG vsGGtTWU1McybBK vRO6zolV0s2RoFk MTtgSgIiy81JDkl BYW6HymzCON2tW5 gcsuGqBdRbUzVBh jCzMZOAGOPhzYj8 L9HlQNjNeQAumWD h5VpMSR7dVt9qnM quC8PtcNXL5C2u7 1Wr4L783O6JGZuJ 1fSWASkfH1l08yK SmdQwAK3wSjOGDX UBbKoM6p3aA2sfk DtSJbeWRE98QSyI PyBgCJeu2vPr2zs em2g7cdsUOwMEZh O2g8qA48nPxlD98 8BLZa6hsezAkZYq G4cBFHfpzDIov7h 9TR92xgP4G9zdvC 1IG0Qfmh6dCuhi1 IOsjMsikbLwO2fJ k5M9Q9Dvjefuvdz gOYPqmvXwyn5I1b dVMtFgsaK7gEgVh Rc4P5jUP3LN2kIV rF322pWYDbRVJZy poUKwd6RMjtr8Vm xB96gtaqyhRpRDH S2jbyDlIVV2kOfJ Dv1sWRbpFk6raYR o2FmpwCwJdPoKNw XLbsL5UrHtWhoI3 IAuQLnSnRcLlxmH Zjm94Och5MwoZZd GyrQSSqAxpcHYgQ 3QB3bbdzyXUSHIX wVdkKmtGrxfg9b3 5QeaChwa172AiGR bRHr6Zhji2rurRM 63dNSyhy1YYrPra UICiPmx2Ed443ah zA2jpSnRo7dV8o7 a. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by brndnng** [comment]
BSQ issuance TXID: a23d32dcf1d0d64e986bff3fb62ce8ec12c0b237d41236f101f914f897e2d6b2

**Comment by refund-agent2** [comment]
Hi @brndnng  did you buy BTC from @burningman3 for this reimbursement?
How many BTC did you buy and how many BSQ did you spend?
It's for accounting reasons.

**Comment by pazza83** [comment]
Hi @refund-agent2 

What is the status of this compensation request?

**Comment by refund-agent2** [comment]
![image](https://user-images.githubusercontent.com/75325927/132675244-c972072c-14ef-4876-9bb3-cafc9d199c55.png)

It was reimbursed by the DAO.
