### ISSUE TITLE
Reimbursement for trade 9nwxc

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#800]
Reimbursement for trade 9nwxc
Trade amount: 2 BTC
Deposit amount: 0.3 BTC
Reimbursement amount: 0.3 BTC  / 0.00006239 BSQ (30-day average) = 4808.46 BSQ
Mediator: bisq_knight 

Issue found here https://github.com/bisq-network/support/issues/752

I do not have ability to release funds for this trade. I interacted with bisq support on January 1st to release funds. MwithM pinged all mediators with no outcome. MwithM alerted me of github thread and told me to post. MwithM has confirmed this is true. https://github.com/bisq-network/support/issues/752#issuecomment-761756317 

Bisq_knight and refundagent2 have verified my wallet ownership. 
https://github.com/bisq-network/support/issues/796#issuecomment-770343878

**Comment by refund-agent2** [comment]
Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.00 BTC
Payout amount for BTC seller: 0.00 BTC

Reason for dispute: Other

Summary notes:
Seller did not respond to mediation and responded late to arbitration because of Bisq data lost, but contacted Support Agent @MwithM into the trading period. Mediator @Bisq-knight did not see the issue and arbitration started. Refund agent was not alerted during arbitration period.
DAO should reimburse the BSQ equivalent to 2.3 BTC to buyer and 0.3BTC to seller. Seller has verified ownership of BTC address used for the trade signing a message with that address.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkZLbxYV kC7EjlRx7IOE5PM dEeQlOO0zXrJt7R 3OEeY1VBjhUYW1u 4D4Tbt4wVRn6JcP 84vofAlh8dzgp7l TaNWvQ2TdwUp2Bv utBitVNuy0RcyB1 SdvPdvND1eAExlt KyKxTraDHoXdFyd YtcVgrRyGWU0xoe LXUn32ndqtNL7cM 1tVqX8rsAoQI5VK xFGXuSKSoxvPHfc 8j2F2xjBTFMyvlG fb8dw1SOCTLsi6g IoiBtl02M6CdGgh U73ZBT3M88sjuzD Lsge9eHnr9TmGmv qRr7Lz22CsE2mCs FqNbkosAdTTziYy RJ6Ws6zYIBKjvW7 eHA0VDVDa7iZ45N QXKjEc6Mu2F83KU Nf38kkYUA16dR3t qbPhfcoTgfFUQIG vsGGtTWU1McybBK vRO6zolV0s2RoFk MTtgSgIiy81JDkl BYW6HymzCON2tW5 gcsuGqBdRbUzVBh jCzMZOAGOPhzYj8 L9HlQNjNeQAumWD h5VpMSR7dVt9qnM quC8PtcNXL5C2u7 1Wr4L783O6JGZuJ 1fSWASkfH1l08yK SmdQwAK3wSjOGDX UBbKoM6p3aA2sfk DtSJbeWRE98QSyI PyBgCJeu2vPr2zs em2g7cdsUOwMEZh O2g8qA48nPxlD98 8BLZa6hsezAkZYq G4cBFHfpzDIov7h 9TR92xgP4G9zdvC 1IG0Qfmh6dCuhi1 IOsjMsikbLwO2fJ k5M9Q9Dvjefuvdz gOYPqmvXwyn5I1b dVMtFgsaK7gEgVh Rc4P5jUP3LN2kIV rF322pWYDbRVJZy poUKwd6RMjtr8Vm xB96gtaqyhRpRDH S2jbyDlIVV2kOfJ Dv1sWRbpFk6raYR o2FmpwCwJdPoKNw XLbsL5UrHtWhoI3 IAuQLnSnRcLlxmH Zjm94Och5MwoZZd GyrQSSqAxpcHYgQ 3QB3bbdzyXUSHIX wVdkKmtGrxfg9b3 5QeaChwa172AiGR bRHr6Zhji2rurRM 63dNSyhy1YYrPra UICiPmx2Ed443ah zA2jpSnRo7dV8o7 a. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by refund-agent2** [comment]
@failedbisqtrade You should post here the transaction ID of your request. Confirm if that's the right one: 70a108868e9f7a486cd88325f0721ee93658496168daeafc1a672f5757334eee

**Comment by refund-agent2** [comment]
Hi @ghost did you buy BTC from @burningman3 for this reimbursement?
How many BTC did you buy and how many BSQ did you spend?
It's for accounting reasons.

**Comment by pazza83** [comment]
Closing as also open here: https://github.com/bisq-network/support/issues/796#issuecomment-770343878
