### ISSUE TITLE
Failed bisq tx, deposited funds locked up in blockchain tx

### ISSUE THREAD

**Issue by CoenKuij** [bisq-network/support#82]
Yesterday I wanted to buy some bitcoin, but after the deposit hit the block chain the tx failed.

Can you please look into this?

Bisq txid = 9985452

**Comment by cbeams** [comment]
Have you opened an arbitration ticket about this, @CoenKuij? If you're unable to do so (because the trade failed before it was possible to open an arbitration ticket), then you'll need to provide us with transaction IDs for Maker / Taker / Deposit transactions. You can find this information by clicking on `Details` / `(i)` in the failed trade. Please copy and paste the tx id values here, and please also take a paste a screenshot of them here. Thanks.

**Comment by CoenKuij** [comment]
No no ticket was opened unfortunately. 
Taker Id (Mine) bacf76ddb7a11747e84ecb492e118ace04231c60c5077cbebb4ea6b5b4ccd77d
Maker Id (other party) 100ea2fc5343e8152a0c945091a0bfdd6ee31c97d1b8348702374829f2a25166

![image](https://user-images.githubusercontent.com/3787397/37364951-3b1d2ed0-26fc-11e8-8b9f-caa0152c69a7.png)

**Comment by cbeams** [comment]
@CoenKuij, this was @keo-bisq's arbitration case, so I'll let him weigh in about what he is doing / has done with it.

In the meantime, though, I'll get this queued up for fee reimbursement in our next batch transaction (#76).

**Comment by keo-bisq** [comment]
I don't have tradeID 9985452 in my arbitration list.

**Comment by CoenKuij** [comment]
@cbeams @keo-bisq How will this now be handled?

**Comment by cbeams** [comment]
@CoenKuij, I see that the transactions you pasted above have indeed ended up in a deposit transaction that was never paid out, meaning that this isn't just about a reimbursement of lost fees, but that it really is about trading funds and security deposits being locked up.

It looks like we'll need to do a manual payout on this, but it'll need to be done a little differently from the [usual instructions](https://docs.bisq.network/manual-dispute-payout.html), because neither @keo-bisq nor I have this trade in our arbitration queues. The main thing I need from you is the full text of the JSON contract for this trade. Can you find that and send it to me over a secure channel? You should be able to find it by going to the trade details on the failed trade and clicking the `View contract in JSON format` button.

You can send this to me securely via Keybase (I'm `@cbeams`), or via encrypted email at chris@beams.io (my PGP key is available via public keyservers). Keybase is best, so we can just continue the chat there and go through the manual payout process together.

**Comment by CoenKuij** [comment]
Settled to full satisfaction. Thank you for your trouble!

**Comment by cbeams** [comment]
Thanks, @CoenKuij. Technically, it wasn't "reimbursed", because the funds never actually left your Bisq wallet. What did get spent (and lost), though, were your taker transaction's mining and trading fees. These are minimal, but still lost, and it's our policy to reimburse them for failed trades. If you'd like to reopen the issue and get reimbursed for these fees, please do, and we'll roll it into the next batch reimbursement transaction (#101). Best regards, and thanks for following up here.

**Comment by CoenKuij** [comment]
@cbeams Ah, I see.
Please refund the fees.

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at #101
