### ISSUE TITLE
Reimbursement for trades SIUT5I, morhk, XFKeX, YFNLU

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#822]
## Reason for reimbursement

On 5th of January, (roughly 10/11 am I believe), I put down a deposit for a few different trades. I turned off the software, launched it again in a about an hour or two, and they were all gone, no trace whatsoever. I lost access to the trade data due to a bug and couldn't reach my trading partner. I opened a Github issue regarding this (https://github.com/bisq-network/support/issues/726) The 20 days for mediation passed and my trading partners sent the ticket to Arbitration where I was wrongly penalized.

I was helped on this issue by @huey735 and the Arbitrator for all trades was @refund-agent2

Total amount: 2262.76 BSQ

## Reimbursement for trade SIUT5I

![SIUT5I](https://user-images.githubusercontent.com/77015544/107639114-5e559e00-6c68-11eb-8bf6-d4435581ea08.png)

I am BTC buyer taker.
Trade amount and asset: 0.08 BTC for 2014 GBP
Deposit amount: 0.012 BTC

Maker:  b8fbe978858645805e1fde0aaa46c000e266d52f9d6245d7957f22cf2e902fc6
Taker: 993054637612c2dbb4612c8b72f2ac39579bad8e930606955542181d0479619d
Security deposit: bcc405c17c3abc0f7317c993e7ed5b72853eeae92167dcdb4d5f44a52ce50107
Delayed payout: 9ea1d0e9a61876a8a557016c28854580fc1b8f12b93c632d1b3000c2743fb785

Reimbursement amount: 0.092 BTC / 0.00007071 BSQ [30 day BSQ average] = 1301.09 BSQ

---------------------

## Reimbursement for trade morhk

![morhk](https://user-images.githubusercontent.com/77015544/107639136-644b7f00-6c68-11eb-97b6-42ef36ae3c3b.png)

I am BTC buyer taker.
Trade amount and asset: 0.01 BTC for 257 GBP
Security deposit amount: 0.006 BTC

Maker:  96a28c00172503885042f381022974eb97cd58bff451746443f3c8f5b395cba9
Taker: 80c005484ebea6fda7f8aa0c1e4e0ac6ba9c851891cc8ea23a31fb2e3178a06b
Deposit: 09c775c7c61dae83e73955b361d92f1b3f5caaa61ee371da69e4bd9743675fdc
Delayed payout: bb58153c357e8e7d8baa2b122916ca9b725129fd5da616a973e6f265cdf63a21

Reimbursement amount: 0.016 BTC / 0.00007071 BSQ [30 day BSQ average] = 226.28 BSQ

---------------------

## Reimbursement for trade XFKeX

![XFKeX](https://user-images.githubusercontent.com/77015544/107639157-69a8c980-6c68-11eb-9486-e392d786355a.png)

I am BTC buyer taker.
Trade amount and asset: 0.03 BTC for 768 GBP
Security deposit amount: 0.006 BTC

Maker:   b9f5a8879418823cfcb1e133279c65db16a4d820c734cce4ee8fe0918765313f
Taker: 10b1e704dd2242114ada632d234b5c4841496af5491592d13be7a156647c2fa6
Deposit: b1658c8c987b01e82a31ab43cf5911b008ae4e4e3bca680bd305370cac699a29
Delayed payout: bb58153c357e8e7d8baa2b122916ca9b725129fd5da616a973e6f265cdf63a21

Reimbursement amount: 0.036 BTC / 0.00007071 BSQ [30 day BSQ average] = 509.12 BSQ

---------------------

## Reimbursement for trade YFNLU

![YFNLU](https://user-images.githubusercontent.com/77015544/107639167-6e6d7d80-6c68-11eb-8af1-3ab86123b974.png)

I am BTC buyer taker.
Trade amount and asset: 0.01 BTC for 256 GBP
Security deposit amount: 0.06 BTC

Maker:  a9cd32cfb35716721342ad4c93925600dd955be03d77f0c30e069a99066ba5dc
Taker: 3581b87f2ca58ab13abee2cd9f2adf45707f5ff79083f232bdec1879ee21f49f
Deposit: b66df3260d98c26e975ec6f72159a47fe4cdeae6158d6a1858fe2215cd4cabfc
Delayed payout: 1532b9a7b28f47457335ed156b497ed18bc4d5bae93667c168304ca392f370e9

Reimbursement amount: 0.016 BTC / 0.00007071 BSQ [30 day BSQ average] = 226.28 BSQ

**Comment by huey735** [comment]
@leo816

**Comment by refund-agent2** [comment]
Hello @Wrecktangl3 

- You need to contact me at Keybase to verify that you own the private keys of your addresses used for this trades so we know that you are who you say you are. My handle is @refundagent2
SIUT5I bc1qj3meulkuuzyzlf4jt8xl2wgdmesgftxhpxmmaj
morhk bc1qngl5wc37xld5rhjjwp2a2tqt0wwggpugxx804p
XFKeX bc1qcr3l2rys5g39nm0jc5gvnjuf92tepnqnks0ag0
YFNLU bc1qfmvdjjqzee2ezh93h4k97zzazyx3zxqvtjnjun

We need to know that  data was lost because of a bug and not intentionally.

BTC buyer never replied to arbitration, that was the summary notes. #726 issue title was "Fee reimbursement for Deposits", so it looked like a regular failed trade request for for lost trading fees, which did not cause any alarm on the support team. I was not notified about this issue.

**Comment by refund-agent2** [comment]
@wr3ck at Keybase verified successfully owning the private keys for this addresses.

**Comment by refund-agent2** [comment]
In my opinion DAO should not reimburse more than 1130BSQ, a half of what the trader suggests, because the way it was reported, it was very hard for the support team to detect that this was a trade reimbursement case and not a fee reimbursement one.
Due to this, the all the funds were refunded to seller, and all reimbursement buyer will come from DAO's budget.
We at Support team need to come with a way to make issues like this not happening again, by reporting and communicating when trading funds are lost.
Also, I would like to know the opinion from more DAO contributors as I should not be the only voice on that issue.

**Comment by huey735** [comment]
Although I agree with @refund-agent2 that the trader didn't properly report the case. I think that part of the responsibility for this ticket to get lost in time lies with the @bisq-network/support team . This may be a case where our compensation should be penalized.

**Comment by SecretiveBat** [comment]
@huey735 and @refund-agent2 I have strong suspicions that @Wrecktangl3 is not being truthful with this request and deliberately misleading the DAO.

Please can DAO check to see if @Wrecktangl3 did in fact make payment for all the above 4 trades? It should be possible to check out trade ID mediation and arbitration tickets to see if payment was in fact made? Also, mediators could reopen mediation tickets with @Wrecktangl3's counterparties to confirm the version of events.

Issue #726 was poorly referenced. Has a genuine bug has been established?

I think refunds in cases like this lead the way to users potentially trying to scam the DAO either by self-trading or by trying to claim what they know they are not entitled to as a result of their own failings.

Hypothetically a scammer could do the following: 

- Take multiple trades on Bisq to buy BTC
- Not make fiat payment for any trades
- Post a vague issue on GitHub with key information missing
- Wait a period of time until a refund agent has been made 
- Raise a request to be compensated by the DAO for the security deposit (paid) and trading amounts (not paid)

Taking it a step further a scammer could then complete self trades with themselves to get paid out twice and not lose security deposit.

DAO should be careful when refunding users that provide incomplete and miss-leading information. There should be an onus on users to provide all the necessary evidence that what they said occurred did actually occur.

@Wrecktangl3 I think you should not be paid out at all for the trades due to my above concerns. I would review my opinion if you can provide the required evidence of your version of events.

**Comment by chimp1984** [comment]
I agree with @SecretiveBat that this case require more solid evidence and double checks from all mediators/arbitrator to be sure about the claim. I will not support that request until there is clear evidence provided.

**Comment by huey735** [comment]
@SecretiveBat @chimp1984 
I, as a non developer, took a look at the trader's logs and they did reference relevant information regarding these trades. I shared these on the bisq.support chat for the devs to take a look and I believe @jmacxx can corroborate it.

However now re-evauluating the above I see that a mistake has been made. Thanks @SecretiveBat for questioning whether did in fact make payment for all the above 4 trades. They didn't. I filled the report for them and following from the template went ahead and included the trade amount. In fact, @Wrecktangl3 confirmed to me to (their support agent and mediator in two cases) that they didn't send the fiat in any of the trades and only have to be reimbursed the security deposit for each trade. Which would amount to **509.12 BSQ**


# 

**Reimbursement for trade SIUT5I**
Trade amount and asset: 0.08 BTC for 2014 GBP
Deposit amount: 0.012 BTC

Reimbursement amount: 0.012 BTC / 0.00007071 BSQ [30 day BSQ average] = 169.70 BSQ


**Reimbursement for trade morhk**
Trade amount and asset: 0.08 BTC for 2014 GBP
Deposit amount: 0.012 BTC

Reimbursement amount: 0.012 BTC / 0.00007071 BSQ [30 day BSQ average] = 169.70 BSQ


**Reimbursement for trade XFKeX**
Trade amount and asset: 0.03 BTC for 768 GBP
Security deposit amount: 0.006 BTC

Reimbursement amount: 0.006 BTC / 0.00007071 BSQ [30 day BSQ average] = 84.86 BSQ


**Reimbursement for trade YFNLU**
Trade amount and asset: 0.01 BTC for 256 GBP
Security deposit amount: 0.006 BTC

Reimbursement amount: 0.006 BTC / 0.00007071 BSQ [30 day BSQ average] = 84.86 BSQ

**Comment by refund-agent2** [comment]
Buyer never did a payment, as buyer couldn't get seller's data after losing Bisq data. I don't know why @Wrecktangl3 has decided to include trade amounts to be reimbursed instead of only security deposits. Sorry, I didn't check the correct amounts of this reimbursement as I was paying more attention to verify identity and if buyer communicated the bug correctly.
The total amount to demand would be 0.03BTC: Security deposit for SIUT5I was 0.012BTC and the other 3, 0.006BTC.
0.03 / 0.00007071 = 424.27 BSQ
I still think that this amount should be reduced to the half, or even more after doing a wrong reimbursement proposal.

**Comment by huey735** [comment]
@refund-agent2 
> I don't know why @Wrecktangl3 has decided to include trade amounts to be reimbursed instead of only security deposits.

That was my mistake.


> The total amount to demand would be 0.03BTC: Security deposit for SIUT5I was 0.012BTC and the other 3, 0.006BTC.
0.03 / 0.00007071 = 424.27 BSQ

Another mistake of mine, you are correct here. For some reason I counted 0.012 twice.

**Comment by Wrecktangl3** [comment]
Hi There Everyone, 

It seems like I may have accidentally caused some confusion with my original post, but I didn't mean for it to be mis-leading, I'm quite new to bisq so I'm not that good with the termonolgy but I did make it quite clear from the beginning especially later on when I was speaking to @huey735 that I was only seeking re-imbursement for the deposit amounts of those trades and not the full trades themselves. I mentioned numerous times that I made deposits for numerous transactions and they were put up on my portfolio, I later closed the program and when I launched it up again, all the transactions were gone. So, I was not reclaiming re-imbursement of the full amount because there was nobody for me to pay to and yet I had still lost my deposit money for those transactions.

**Comment by SecretiveBat** [comment]
Thanks, @Wrecktangl3 for clarifying your original post.

I still think more information is needed to come to a decision on this refund request. It would be helpful to know the following:

@Wrecktangl3 are you now claiming for 0.03 BTC (424.27 BSQ)?

@huey735 did @Wrecktangl3 provide you with enough information on Keybase on 5th Jan to be able to verify there had been a bug in Bisq?

@huey735 did @Wrecktangl3 provide you with enough information on Keybase on 5th Jan to know that they had taken 4 trades? and if so were any attempts made to contact the mediator for those trades?

I think it is important to establish what has gone wrong with the trade.

It should be considered:

1. How much personal responsibility traders have for their own trades
2. How much Bisq is liable for Bugs (I am assuming it is liable if bug are quickly identified) 
3. How much Bisq is liable for the support provided

If Bisq is liable for 2, and 3 above I think a proportion of the payouts made by the refund agents where one party is not communicating should be donated to the DAO in the way of burning BSQ. This would provide a sort of insurance for situations if or when Bisq is liable for users losing funds.

**Comment by chimp1984** [comment]
Can anyone involved with the support case explain why the data has been lost? I am not aware that such ever happened and I highly doubt that this can happen due a bug. 
I prefer to postpone that request to the next voting cycle if we do not manage to get a clear picture before voting starts. Doing reimbursements without enough care and due dilligence is a dangerous avenue for the DAO.

**Comment by jmacxx** [comment]
Hi, I looked into this on the Bisq.support keybase channel `open-trade-info-lost`, on 11th Feb.  At the time I concluded that it looked like an older Bisq backup had been restored, overwriting the relevant part of the log file, and reverting the database state such that the trades would not be available to be shown.

---

However, since that time more information has come to light from another support case which resulted in issue https://github.com/bisq-network/bisq/issues/5257 being opened.  Now looking again at the log file of this case it shares significant similarities such that I now am fully convinced this case is exactly the same issue.  The symptom is that two Bisq processes are able to be opened at almost the same time, causing the data loss/overwrite.

**Comment by chimp1984** [comment]
@jmacxx Ah thanks! Yes the linked issues seems to be a serious one and might explain this case then.

**Comment by Wrecktangl3** [comment]
Hi @SecretiveBat,
I'm not sure what more information you would want me to provide, I did everything both @huey735 and @refund-agent2 asked of me. However, if there is other processes you need me to go through, I would be happy to comply, just know that I am quite new to the whole cypto/bisq scene and need some help/ assistance going through some of your processes.
As for the the Reimbursement, I'm not too familiar with the Bsq currency system but as mentioned before, I am only claiming what I lost through the deposits I made. You have calculated that to be 0.03 BTC where as I lost 0.032575 BTC, however I think you have your own special method of calculating reimbursement fees.
