### ISSUE TITLE
PORTFOLIO / MY OPEN OFFERS issue

### ISSUE THREAD

**Issue by Ex0ticButt3rs** [bisq-network/support#948]
My open offers are disabling themselves randomly. There is no trigger price set. I did test out the trigger price functionality earlier today yet updated all offers recently to have a blank trigger price. 

Currently, the majority of my offers are switching themselves from on to off. 

Questions:
1 - Is this a known bug/issue? 
2 - What could be the root cause?
3 - What do I need to do to stop this from happening (as I do want all my offers to be active)?

**Comment by jmacxx** [comment]
Go to `DAO -> Network Monitor` menu, see if it says you need to resync under DAO State.

**Comment by Ex0ticButt3rs** [comment]
> Go to `DAO -> Network Monitor` menu, see if it says you need to resync under DAO State.

DAO State / Status = "One of your peers is not in consensus with the network but your node is in sync with the seed nodes."
![Screen Shot 2021-06-22 at 11 44 00 PM](https://user-images.githubusercontent.com/86173897/123032320-c0ab7180-d3b3-11eb-83c5-79932215a42b.png)

**Comment by jmacxx** [comment]
Please DM me your bisq.log on Keybase, I have this same username on there.  The log location can be found by going to `Application -> Backup`

**Comment by Ex0ticButt3rs** [comment]
Done. Please do let me know if I can provide any additional information/data.

![Screen Shot 2021-06-23 at 9 00 33 AM](https://user-images.githubusercontent.com/86173897/123100989-98e2fa80-d401-11eb-9638-c9bf8809f640.png)

**Comment by jmacxx** [comment]
The problem is caused by confusion in the Bisq app about what addresses are authorized to receive Bisq trading fee payments.

A [recent change](https://github.com/bisq-network/projects/issues/31#issuecomment-866297498) ending the April 2020 incident repayment shortened that list of fee receiver addresses, but since there are still open offers, Bisq thought the fees were not paid correctly and so disabled the offers.

To address this discrepancy, we've temporarily turned off the fee validation feature via a network filter setting.  It might take up to 24 hours for the configuration change to propagate fully, please be patient if not resolved immediately.  The Bisq client needs to be restarted in order to pick up the change.  Once your Bisq client picks up the network setting, it will stop deactivating your offers.
